---
# Start testing reachability

- name: Update apt cache everywhere
  hosts: management,k8s_cluster

  tasks:
    - name: "Refresh apt cache"
      ansible.builtin.apt:
        update_cache: true

- name: Deploy Kubernetes Dependencies
  hosts: management,k8s_cluster

  vars:
    k8s_version: "v1.32"
    k8s_apt_url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb"
    k8s_apt_key: "/etc/apt/keyrings/kubernetes-apt-release.key"
    k8s_apt_gpg: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"

  roles:
    - common
    - containers
    - kubernetes

- name: Deploy Helm
  hosts: management,control_nodes

  vars:
    helm_apt_url: "https://baltocdn.com/helm"
    helm_apt_key: "/etc/apt/keyrings/helm-apt-release.key"
    helm_apt_gpg: "/etc/apt/keyrings/helm-apt-keyring.gpg"

  roles:
    - helm
